#!/usr/bin/env bash
# Convert 'pass' passwords to csv

shopt -s nullglob globstar
prefix=${PASSWORD_STORE_DIR:-$HOME/.password-store/}

# create the column row
echo -e "Title\tUsername\tPassword" >> exported_passes.csv

for file in "$prefix"/**/*.gpg; do                           
    file="${file#$prefix}"
    title=$( basename $( dirname "$file" ) )
    username=$( basename -s .gpg "$file" )
    password=$( pass "${file%.*}" )
    printf "%s\t%s\t%s\n" "$title" "$username" "$password" >> exported_passes.csv
    echo "Exporting $title"
done

echo
echo "Completed exporting"
