#!/usr/bin/env bash

lines=$( swaymsg -t get_tree | jq 'recurse(.nodes[]) | if .app_id != null then {(.app_id): .pid} else null end' | awk 'BEGIN{FS=":"} !/^null|^\{|^}/{print $1" (pid:"$2")"}' )

[ -z "$lines" ] && exit 1
choice=$( echo -e "$lines" | wofi -d -p "Where to switch focus?" | awk 'BEGIN{FS=": "} {print $2}')
[ -z "$choice" ] && exit 1

jump_id="${choice:: -1}"

swaymsg "[pid=$jump_id] focus"
