#!/usr/bin/env bash

[ -d "/tmp/gaps" ] || mkdir /tmp/gaps

current_workspace=$( swaymsg -t get_workspaces | jq '.[] | select(.focused==true) | .name' | tr -d '": ' )

if ! [ -e "/tmp/gaps/workspace_$current_workspace" ]; then
    gaps_state=1
else
    gaps_state=$( cat /tmp/gaps/workspace_$current_workspace )
fi


if [ "$gaps_state" -eq 1 ]; then
    swaymsg "gaps inner current set 0"
    swaymsg "gaps outer current set 0"
    echo 0 > /tmp/gaps/workspace_$current_workspace
else
    swaymsg "gaps inner current set 18"
    swaymsg "gaps outer current set 18"
    echo 1 > /tmp/gaps/workspace_$current_workspace
fi
